version: 2
jobs:
  build:
    macos:
      xcode: 9.4.1
    steps:
      - checkout
      - run:
          name: Run tests
          command: xcodebuild test -destination "platform=iOS Simulator,name=iPhone 7" -workspace Example/SwiftLuhn.xcworkspace -scheme SwiftLuhn-Example | xcpretty
      - run:
          name: Verify valid podspec
          command: pod lib lint --swift-version=4.0
